name: Package - Lambda 1

on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    paths:
      - 'lambdas/lambda1/CHANGELOG.md'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CURRENT_HASH: ${{ github.sha }}

jobs:
  extract_version:
    if: github.event.pull_request.merged && startsWith(github.event.pull_request.head.ref, 'release-please--branches--main--components--')
    runs-on: ubuntu-latest
    outputs:
      package_version: ${{ steps.extract_version.outputs.version }}
    steps:
      - uses: actions/checkout@v3
      - name: Install jq
        run: sudo apt-get install jq
      - name: Extract version from package.json and set as output
        id: extract_version
        run: |
          VERSION=$(jq -r '.version' lambdas/lambda1/package.json)
          echo "::set-output name=version::$VERSION"

  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: is_runnable
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: cd lambdas/lambda1 && npm ci --ignore-scripts
      - run: cd lambdas/lambda1 && npm test

  audit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    needs: is_runnable
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: cd lambdas/lambda1 && npm ci --ignore-scripts
      - run: cd lambdas/lambda1 && npm audit --omit=dev

  publish_release:
    needs: [extract_version, test, audit]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Extract metadata (tags, labels) for Docker
        id: meta-secret-rotation
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/test-lambda-1
      - name: Build and push Docker image (Secret Rotation Function)
        uses: docker/build-push-action@v5
        with:
          context: ./lambdas/lambda1
          file: ./lambdas/lambda1/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/test-lambda-1:latest
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/test-lambda-1:${{ needs.extract_version.outputs.package_version }}
          labels: ${{ steps.meta-secret-rotation.outputs.labels }}
          build-args: |
            GITHUB_PACKAGE_ACCESS_TOKEN=${{ secrets.GH_PACKAGE_ACCESS_TOKEN }}