on:
  pull_request:
    types: [closed]
    branches:
      - 'main'
    # paths:
    #   - 'lambdas/lambda1/**'

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}
  CURRENT_HASH: ${{ github.sha }}

name: Analyze and Release
jobs:
  test:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: cd lambdas/lambda1 && npm ci --ignore-scripts
      - run: cd lambdas/lambda1 && npm test

  audit:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: 'https://npm.pkg.github.com'
      - run: cd lambdas/lambda1 && npm ci --ignore-scripts
      - run: cd lambdas/lambda1 && npm audit --omit=dev

  create_release:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
    steps:
      - uses: google-github-actions/release-please-action@v4
        id: release
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Print release outputs
        run: |
          echo "Release created: ${{ steps.release.outputs.release_created }}"
          echo "Tag name: ${{ steps.release.outputs.tag_name }}"